baseURL = "/"
title = "TB Logistica S.r.l."
author = "Manuel"
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
theme = "tella"
enableRobotsTXT = true
enableEmoji = true

# Please enable this feature if the site is available in Japanese, Chinese or Korean.
#hasCJKLanguage = true

# If you're using Google Analytics, you can enable this feature.
#googleAnalytics = "UA-12345678-1"

# Disqus Comment System
#disqusShortname = ""   

[params]

  showBlog = true
  mainSections = ['blog']

  googleFonts = true

  [params.logo]
    main = "img/logo/image.png"
    alt = "TB Logo"

    # The size parameter is the class name of tailwindcss
    # https://tailwindcss.com/
    size = "h-auto"

  [params.site]
    name = "TB Logistica"

  [params.icon]
    #If you want to use FontAwesome, set this parameter to true.
    fontawesome = true

  [params.homepage_meta_tags]
    meta_description = "TB Logistica Srl azienda di trasporti specializzata nel trasporti animali a Cuneo"
    meta_og_title = "TB Logistica srl"
    meta_og_type = "website"
    meta_og_url = "/blog"
    meta_og_image = "/img/logo/image.png"
    meta_og_description = "TB Logistica trasporto Cuneo"
    meta_twitter_card = "summary_large_image"
    meta_twitter_site = "@username"
    meta_twitter_creator = "@username"

[menu]

  [[menu.main]]
    identifier = "products"
    name = "Galleria Fotografica"
    url = "/products/gallery/"
    weight = 3

  [[menu.main]]
    identifier = "blog"
    name = "Servizi"
    url = "/blog/"
    weight = 2

  [[menu.main]]
    identifier = "about"
    name = "La Nostra Storia"
    url = "/about/"
    weight = 1

  [[menu.main]]
    identifier = "contact"
    name = "Contatti"
    url = "/contact/"
    weight = 4

  # Footer Menu
  [[menu.footer]]
    name = "Home"
    url = "/"
      weight = 1

  [[menu.footer]]
   name = "info@tblogisticasrl.it"
   url = "mailto:info@tblogisticasrl.it"
   weight = 7

  [[menu.footer]]
  name = "Instagram"
  pre = "<i class = 'fab fa-instagram'></i>"
  url = "https://www.instagram.com/bikenorthbergen/"
  weight = 3
  
  [[menu.footer]]
   name = "YouTube"
   pre = "<i class = 'fab fa-youtube'></i>"
   url = "https://www.youtube.com/channel/UC_GroPWrqSTQIoMOF7jdU0Q"
   weight = 4
  
  [[menu.footer]]
   name = "Facebook"
   pre = "<i class = 'fab fa-facebook'></i>"
   url = "https://www.facebook.com/Bike-North-Bergen-108227921644201/"
   weight = 5

  [[menu.footer]]
   name = "Linktree"
   pre = "<i class = 'fas fa-link'></i>"
   url = "http://www.assemblercomputer.net/"
   weight = 6  
   