[build]
  publish = "public"
  command = "git submodule update --remote --merge && npm run build"

[build.environment]
  HUGO_VERSION = "0.124.1"
  NODE_VERSION = "22"

[context.production.environment]
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.split1]
  command = "npm run build"

[context.split1.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "npm run build"

[context.deploy-preview.environment]
  HUGO_ENV = "production"

[context.branch-deploy]
  command = "npm run build"

[context.branch-deploy.environment]
  HUGO_ENV = "production"

[context.next.environment]
  HUGO_ENABLEGITINFO = "true"