[build]
  command = "hugo --gc --minify"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.126.1"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

# (Opzionale) www → non-www o viceversa
[[redirects]]
  from = "https://www.tblogisticasrl.net/*"
  to = "https://tblogisticasrl.net/:splat"
  status = 301
  force = true

# (Opzionale) vecchi slug in inglese → nuovi in italiano
[[redirects]]
  from = "/contact"
  to = "/contatti/"
  status = 301
[[redirects]]
  from = "/services"
  to = "/#servizi"
  status = 301
[[redirects]]
  from = "/gallery"
  to = "/#galleria"
  status = 301