[build]
  command = "hugo --gc --minify"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.126.1"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

# Canonical: www -> non-www
[[redirects]]
  from = "https://www.tblogisticasrl.net/*"
  to   = "https://tblogisticasrl.net/:splat"
  status = 301
  force  = true

# Vecchi slug -> nuove sezioni
[[redirects]]
  from = "/contact"
  to   = "/contatti/"
  status = 301
  force  = true

[[redirects]]
  from = "/services"
  to   = "/#servizi"
  status = 301
  force  = true

# Galleria: qualunque tentativo /galleria o /gallery va all’anchor in home
[[redirects]]
  from = "/galleria"
  to   = "/#galleria"
  status = 301
  force  = true

[[redirects]]
  from = "/galleria/"
  to   = "/#galleria"
  status = 301
  force  = true

[[redirects]]
  from = "/gallery"
  to   = "/#galleria"
  status = 301
  force  = true

[[redirects]]
  from = "/gallery/"
  to   = "/#galleria"
  status = 301
  force  = true